dataset: 
  name: cvact
  dataset_root_dir: 'data/CVACT_full'
  dataset_version: 'mini'
  n_workers: 4

model: 
  name: simsiam
  backbone: vgg16
  pool: flatten
  shared: False
  category: 'satellite'
  img_size_w: 512
  img_size_h: 112

train:
  seed: null # None type for yaml file
  # two things might lead to stochastic behavior other than seed:
  # worker_init_fn from dataloader and torch.nn.functional.interpolate 
  # (keep this in mind if you want to achieve 100% deterministic)
  batch_size: 128
  n_epochs: 30 # this parameter influence the lr decay
  start_epoch: 0
  eval_every: 1
  patience: 5
  save_every_epoch: False
  threads: '4'
  gpu_ids: '3'
  no_cuda: False
  n_gpu: 1
  save_path: 'work_dirs'
  # save_path: 'work_dirs_for_debug'
  resume_path: ''
  # resume_path: 'work_dirs/May07-0032_simsiam_vgg16_max_shared_None_cvact_mini/checkpoints/checkpoint.pth.tar'
  load_path: ''
  # load_path: 'work_dirs/May12-2141_simsiam_vgg16_flatten_noshared_ground_cvact_mini/checkpoints/checkpoint.pth.tar'
  load_sep_branch: False
  train_as_val: False
  grad_cam: False
  extra_identifier: 'noimagenet'

hyperparams:
  optim: 'sgd'
  weight_decay: 0.0005
  momentum: 0.9
  warmup_epochs: 1
  warmup_lr: 0
  base_lr: 0.03
  final_lr: 0