dataset:
  name: vigor
  dataset_root_dir: 'data/VIGOR'
  version: ''
  n_workers: 1
  train_loader_shuffle: True

model:
  name: cvm
  backbone: vgg16
  pool: max
  shared: False
  img_size_w: 512
  img_size_h: 112

train:
  seed: 42
  batch_size: 8
  n_epochs: 80
  start_epoch: 0
  eval_every: 1
  patience: 0
  save_every_epoch: False
  threads: '1'
  gpu_ids: '6'
  n_gpu: 1
  # save_path: 'work_dirs'
  save_path: 'work_dirs_for_debug'
  resume_path: ''
  load_path: ''
  
  load_sep_branch: False
  load_only_backbone: False
  train_as_val: False
  only_val: False
  grad_cam: False
  check_align_and_uniform: True
  extra_identifier: ''

hyperparams:
  optim: 'adam'
  weight_decay: 0.001
  momentum: 0.9
  lr: 0.0001
  lr_step: 5
  lr_gamma: 0.5
  margin: 0.1