identifier: 'crossview_vgg16_max_cvact'

dataset:
  name: cvact
  dataset_root_dir: 'data/CVACT_full'
  dataset_version: '1k'
  n_workers: 4

model:
  name: crossview
  backbone: vgg16
  pool: max
  img_size_w: 616
  img_size_h: 112

train:
  seed: 123
  batch_size: 16
  n_epochs: 80
  start_epoch: 0
  eval_every: 5
  patience: 0
  save_every_epoch: False
  threads: '6'
  gpu_ids: '2'
  no_cuda: False
  n_gpu: 1
  save_path: 'work_dirs'
  # save_path: 'work_dirs_for_debug'
  resume_path: ''
  # resume_path: 'work_dirs/Apr27_00-59-08_crossview_vgg16_safa_cvact/checkpoints/checkpoint.pth.tar'
  train_as_val: False

hyperparams:
  optim: 'adam'
  weight_decay: 0.001
  momentum: 0.9
  lr: 0.0001
  lr_step: 5
  lr_gamma: 0.5
  # margin for hard triplet loss (deprecated)
  margin: 0.1