dataset:
  name: vigor
  dataset_root_dir: 'data/VIGOR'
  version: 'newfull'
  n_workers: 32

model:
  name: cvm
  backbone: vgg16
  pool: fc
  imagenet: True

train:
  seed: 42
  batch_size: 96
  n_epochs: 150
  start_epoch: 0
  eval_every: 3
  patience: 0
  save_every_epoch: True
  threads: '2'
  gpu_ids: '0'
  n_gpu: 1
  slurm: True
  save_path: 'work_dirs'
  # save_path: 'work_dirs_for_debug'
  resume_path: ''
  # resume_path: 'work_dirs/Jun14-0425_cvm_vgg16_fc_vigor_newfull/checkpoints/checkpoint_epoch60.pth.tar'
  # resume_path: 'work_dirs/Jun13-1620_cvm_vgg16_fc_vigor_newfull/checkpoints/checkpoint_epoch60.pth.tar'
  
  # resume_path: 'work_dirs/Jun27-1644_cvm_vgg16_fc_vigor_newfull/checkpoints/checkpoint_epoch99.pth.tar'
  # resume_path: 'work_dirs/Jun27-1647_cvm_vgg16_fc_vigor_newfull/checkpoints/checkpoint_epoch99.pth.tar'
  # resume_path: 'work_dirs/Jun27-2314_cvm_vgg16_fc_vigor_newfull/checkpoints/checkpoint_epoch99.pth.tar'
  # resume_path: 'work_dirs/Jun27-2328_cvm_vgg16_fc_vigor_newfull/checkpoints/checkpoint_epoch99.pth.tar'
  # resume_path: 'work_dirs/Jun27-2338_cvm_vgg16_fc_vigor_newfull/checkpoints/checkpoint_epoch99.pth.tar'
  
  load_path: ''
  # load_path: 'work_dirs/Jun12-1946_cvm_vgg16_fc_vigor_newfull/checkpoints/model_best.pth.tar'
  # load_path: 'work_dirs/Jun12-2248_cvm_vgg16_fc_vigor_newfull/checkpoints/model_best.pth.tar'
  # load_path: 'assets/pretrained_models/checkpoint_0099.pth.tar'
  load_sep_branch: False
  load_sep_branch_single: ''
  load_only_backbone: False
  train_as_val: False
  only_val: False
  start_with_val: True
  grad_cam: False
  check_align_and_uniform: True
  extra_identifier: ''

hyperparams:
  optim: 'adam'
  weight_decay: 0.001
  momentum: 0.9
  lr: 0.0001
  lr_step: 5
  lr_gamma: 0.5
  margin: 0.1